version: '3.7'

services:
  flaskapp:
    build: .
    container_name: csvanalytics
    expose:
      - "5001"
    environment:
      - CSV_ENV=production
    volumes:
      - .:/app
    networks:
      - csv_network

  nginx:
    image: nginx:latest
    container_name: csv_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - flaskapp
    networks:
      - csv_network

networks:
  csv_network:
    driver: bridge
