version: '3.7'

services:
  flaskapp:
    build: .
    container_name: csvanalytics
    ports:
      - "6000:6000"
    environment:
      - CSV_ENV=production
    volumes:
      - .:/app
    networks:
      - csv_network

networks:
  flask_network:
    driver: bridge